# Generated by Django 2.1.7 on 2019-03-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_No', models.CharField(max_length=6)),
                ('Item_Code', models.CharField(max_length=6)),
                ('Description', models.CharField(max_length=100)),
                ('Weight', models.FloatField()),
                ('Receiver_Name', models.CharField(max_length=200)),
                ('Receiver_Add', models.CharField(max_length=300)),
                ('Order_date', models.DateTimeField(auto_now=True)),
                ('Deliver_date', models.DateTimeField()),
            ],
        ),
    ]
