# Generated by Django 2.1.7 on 2019-04-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryinfo_delivery_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination', models.CharField(max_length=100)),
                ('Distance', models.IntegerField()),
            ],
        ),
    ]
