# Generated by Django 2.1.7 on 2019-04-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliverydistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='Delivery_Process',
            field=models.CharField(choices=[('Request', 'Request'), ('OnProcess', 'Processing'), ('onDelivery', 'on Delivery'), ('Delivered', 'Delivered')], default='Request', max_length=100),
        ),
    ]
