# Generated by Django 2.1.7 on 2019-04-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20190417_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='District',
            field=models.CharField(choices=[('Colombo', 'Colombo'), ('Gampaha', 'Gampaha'), ('Kalutara', 'Kalutara'), ('Kandy', 'Kandy')], default='Colombo', max_length=100),
        ),
    ]
