# Generated by Django 2.1.7 on 2019-04-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliveryinfo_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydistance',
            name='Price',
            field=models.FloatField(default=50),
        ),
    ]
