# Generated by Django 2.1.7 on 2019-04-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_deliverydistance_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydistance',
            name='Price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='District',
            field=models.CharField(choices=[('Colombo', 'Colombo'), ('Gampaha', 'Gampaha'), ('Kalutara', 'Kalutara'), ('Kandy', 'Kandy')], max_length=100),
        ),
    ]
