# Generated by Django 2.1.7 on 2019-04-30 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20190430_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.DeliveryDistance'),
        ),
    ]
