# Generated by Django 2.1.7 on 2019-05-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_address',
            name='Delivery_Process',
            field=models.CharField(choices=[('Request', 'Request'), ('OnProcess', 'Processing'), ('onDelivery', 'on Delivery'), ('Delivered', 'Delivered')], default='Request', max_length=100),
        ),
    ]
