# Generated by Django 2.1.7 on 2019-05-15 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_timestamp'),
        ('delivery', '0010_delivery_address_delivery_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_address',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.Order'),
        ),
    ]
