# Generated by Django 2.1.7 on 2019-05-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_delivery_address_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_address',
            name='Order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
