# Generated by Django 2.1.7 on 2019-03-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('nic', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=400)),
                ('supplier_item', models.CharField(choices=[('A', 'Stones'), ('B', 'Gold'), ('C', 'Silver'), ('D', 'Colour Stones')], max_length=2)),
            ],
        ),
    ]
