# Generated by Django 2.1.7 on 2019-04-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone_No',
            field=models.IntegerField(default=0),
        ),
    ]
