# Generated by Django 2.1.7 on 2019-03-12 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earrings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NE', 'Necklaces'), ('RI', 'Ring'), ('PE', 'Pendants'), ('ER', 'Earrings')], max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('description', models.CharField(max_length=500)),
                ('charges', models.IntegerField()),
                ('stones', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('craft_id', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item Sold'), ('RESTOCKING', 'Item restocking in few days')], default='SOLD', max_length=10)),
                ('issues', models.CharField(default='No issues', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='jewelry_image/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Necklaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NE', 'Necklaces'), ('RI', 'Ring'), ('PE', 'Pendants'), ('ER', 'Earrings')], max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('description', models.CharField(max_length=500)),
                ('charges', models.IntegerField()),
                ('stones', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('craft_id', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item Sold'), ('RESTOCKING', 'Item restocking in few days')], default='SOLD', max_length=10)),
                ('issues', models.CharField(default='No issues', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='jewelry_image/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pendants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NE', 'Necklaces'), ('RI', 'Ring'), ('PE', 'Pendants'), ('ER', 'Earrings')], max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('description', models.CharField(max_length=500)),
                ('charges', models.IntegerField()),
                ('stones', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('craft_id', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item Sold'), ('RESTOCKING', 'Item restocking in few days')], default='SOLD', max_length=10)),
                ('issues', models.CharField(default='No issues', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='jewelry_image/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NE', 'Necklaces'), ('RI', 'Ring'), ('PE', 'Pendants'), ('ER', 'Earrings')], max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('description', models.CharField(max_length=500)),
                ('charges', models.IntegerField()),
                ('stones', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('craft_id', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item Sold'), ('RESTOCKING', 'Item restocking in few days')], default='SOLD', max_length=10)),
                ('issues', models.CharField(default='No issues', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='jewelry_image/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
