# Generated by Django 2.1.5 on 2019-03-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jewelry',
            old_name='craft_id',
            new_name='craftsman_id',
        ),
        migrations.RenameField(
            model_name='jewelry',
            old_name='qty',
            new_name='quantity',
        ),
    ]
