# Generated by Django 2.1.5 on 2019-03-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Necklaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('charges', models.IntegerField()),
                ('stones', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('craft_id', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item Sold'), ('RESTOCKING', 'Item restocking in few days')], default='SOLD', max_length=10)),
                ('issues', models.CharField(default='No issues', max_length=100)),
                ('image', models.FileField(null=True, upload_to='jewelry_image/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Necleces',
        ),
        migrations.AddField(
            model_name='earrings',
            name='image',
            field=models.FileField(null=True, upload_to='jewelry_image/'),
        ),
        migrations.AddField(
            model_name='pendants',
            name='image',
            field=models.FileField(null=True, upload_to='jewelry_image/'),
        ),
        migrations.AddField(
            model_name='ring',
            name='image',
            field=models.FileField(null=True, upload_to='jewelry_image/'),
        ),
    ]
