# Generated by Django 2.1.5 on 2019-03-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190306_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earrings',
            name='image',
            field=models.ImageField(null=True, upload_to='jewelry_image/'),
        ),
        migrations.AlterField(
            model_name='necklaces',
            name='image',
            field=models.ImageField(null=True, upload_to='jewelry_image/'),
        ),
        migrations.AlterField(
            model_name='pendants',
            name='image',
            field=models.ImageField(null=True, upload_to='jewelry_image/'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='image',
            field=models.ImageField(null=True, upload_to='jewelry_image/'),
        ),
    ]
