# Generated by Django 2.1.5 on 2019-03-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190312_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
