# Generated by Django 2.1.5 on 2019-03-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190316_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='charges',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='weight',
            field=models.FloatField(),
        ),
    ]
