# Generated by Django 2.1.7 on 2019-04-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='jType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jtype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='stone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.jType'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='craftsman_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='craftsmen.craftsmen'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jewelry_image/'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item Sold'), ('RESTOCKING', 'Item restocking in few days')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='stoneType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stone'),
        ),
    ]
