# Generated by Django 2.0.6 on 2019-05-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20190416_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='NoOfStones',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
