# Generated by Django 2.1.7 on 2019-03-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_ID', models.CharField(max_length=255)),
                ('First_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Phone_Number', models.IntegerField()),
                ('Admission_date', models.DateField()),
                ('Job_title', models.CharField(max_length=255)),
                ('Job_level', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
