# Generated by Django 2.1.7 on 2019-05-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanage', '0002_auto_20190312_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='Emp_ID',
        ),
        migrations.AddField(
            model_name='staff',
            name='NIC',
            field=models.CharField(default=123456, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='Admission_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
