# Generated by Django 2.1.7 on 2019-04-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trans_ID', models.CharField(max_length=255)),
                ('Trans_Date', models.DateField()),
                ('Bank_Name', models.CharField(max_length=255)),
                ('Bank_Branch', models.CharField(max_length=255)),
                ('Amount', models.FloatField()),
                ('Withdraw_or_Deposit', models.CharField(choices=[('W', 'Withdraw'), ('D', 'Deposite')], max_length=100)),
                ('Trans_Type', models.CharField(choices=[('Online', 'Online'), ('Cheque', 'Cheque'), ('At Bank', 'At Bank')], max_length=100)),
                ('Transfer_Details', models.CharField(max_length=255)),
            ],
        ),
    ]
