# Generated by Django 2.1.7 on 2019-05-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivering_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
