# Generated by Django 2.1.7 on 2019-03-03 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190303_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online_Customer',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tel_number', models.IntegerField(unique=True)),
                ('address', models.TextField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='test1@test.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='test1', max_length=256),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='test', max_length=256),
        ),
        migrations.AddField(
            model_name='customer',
            name='tel_number',
            field=models.IntegerField(default='0712345678', unique=True),
        ),
    ]
