# Generated by Django 2.1.7 on 2019-03-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190303_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
