# Generated by Django 2.1.7 on 2019-05-09 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAcc',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('im', models.BooleanField(default=False)),
                ('hrm', models.BooleanField(default=False)),
                ('dm', models.BooleanField(default=False)),
                ('cm', models.BooleanField(default=False)),
                ('sm', models.BooleanField(default=False)),
                ('supm', models.BooleanField(default=False)),
            ],
        ),
    ]
