# Generated by Django 2.1.7 on 2019-03-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='test1@test.com', max_length=254, unique=True)),
                ('first_name', models.CharField(default='test1', max_length=256)),
                ('last_name', models.CharField(default='test', max_length=256)),
                ('tel_number', models.IntegerField(default='0712345678', unique=True)),
            ],
        ),
    ]
